MisRecetasMT/Controllers/RecetasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MisRecetasMT.Models.AccesoDB;
using MisRecetasMT.Models.Entidades;
using MisRecetasMT.ViewModels.Receta;


namespace MisRecetasMT.Controllers
{
    //[Authorize]
    public class RecetasController : Controller
    {
        private readonly Contexto _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public RecetasController(Contexto context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Recetas
        
        public async Task<IActionResult> Index()
        {
            
            if((HttpContext.Session.GetInt32("_Rol")==1))            
                return View(await _context.Recetas.Include("Usuario").ToListAsync());
            else
                return View(await _context.Recetas.Where(x => x.UsuarioId.Equals(HttpContext.Session.GetString("_Id"))).Include("Usuario").ToListAsync());
            
            //return View(await _context.Recetas.Include("Usuario").ToListAsync());
        }

        public async Task<IActionResult> RecetasCompartidas()
        {            
            return View(await _context.Recetas.Include("Usuario").Where(x=>x.Estado==true).ToListAsync());            
        }

        // GET: Recetas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receta = await _context.Recetas.Include(e=>e.Usuario)
                .FirstOrDefaultAsync(m => m.RecetaId == id);
            if (receta == null)
            {
                return NotFound();
            }

            ViewData["RecetaDetalle"] = await _context.RecetaDetalle.Where(x => x.RecetaId == id).Include(y => y.Ingrediente).ToListAsync();

            return View(receta);
        }

        // GET: Recetas/Create
        public IActionResult Create()
        {
            ViewBag.Ingredientes = _context.Ingredientes.Where(x=>x.EstadoIngrediente==true).ToList();
            return View();
        }

        // POST: Recetas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Create([FromBody] RecetaViewModel recetaViewModel)
        //public IActionResult Create([FromBody] IFormFile file)
        //public IActionResult Create (IFormFile file)
        //public IActionResult Create(RecetaViewModel recetaViewModel)
        //public JsonResult Create(string Nombre, string Descripcion, IFormFile Imagen, List<RecetaDetalle> Ingredientes)
        public async Task<IActionResult> Create(string Nombre, string Descripcion, IFormFile Imagen, bool Estado)
        {                        
            
            if (Nombre != null && Descripcion != null && Imagen != null)
            {
                Receta receta = new Receta();
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string nombreImagen = Path.GetFileNameWithoutExtension(Imagen.FileName);
                string extension = Path.GetExtension(Imagen.FileName);
                receta.NombreImagen = nombreImagen = DateTime.Now.ToString("yymmssfff") + extension;
                receta.Nombre = Nombre;
                receta.Estado = Estado;
                receta.Descripcion = Descripcion;
                receta.Fecha = DateTime.Now;
                receta.UsuarioId = HttpContext.Session.GetString("_Id");                        

                string path = Path.Combine(wwwRootPath + "/image/" + nombreImagen);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await Imagen.CopyToAsync(fileStream);
                }

                _context.Add(receta);

                if (_context.SaveChanges() > 0)
                {
                    return Json(new { data = "ok" });
                }
                else
                {
                    return Json(new { data = "error" });

                }
            }
            else            

                return Json(new { data = "error" });  

        }       

        [HttpPost]
        public IActionResult CreateDetails([FromBody] RecetaViewModel recetaViewModel)
        {
            if (recetaViewModel.Ingredientes != null)
            {
                int RecetaId = _context.Recetas.Max(r => r.RecetaId);

                foreach (var ingrediente in recetaViewModel.Ingredientes)
                {
                    RecetaDetalle recetaDetalle = new RecetaDetalle()
                    {
                        RecetaId = RecetaId,
                        IngredienteId = ingrediente.IngredienteId,
                        Cantidad = ingrediente.Cantidad
                    };
                    _context.Add(recetaDetalle);
                }
                if (_context.SaveChanges() > 0)
                {
                    return Json(new { data = "ok" });
                   
                }
                else
                {
                    return Json(new { data = "no" });
                }
            }
            else
            {
                return Json(new { data = "no" });
            }
         
        }
            // GET: Recetas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receta = await _context.Recetas.FindAsync(id);
            if (receta == null)
            {
                return NotFound();
            }
            RecetaViewModel recetaViewModel = new RecetaViewModel
            {
                RecetaId = receta.RecetaId,
                Nombre = receta.Nombre,
                Descripcion = receta.Descripcion,
                NombreImagen = receta.NombreImagen,
                Estado = receta.Estado,
                UsuarioId = receta.UsuarioId

            };

            ViewData["RecetaDetalle"] = await _context.RecetaDetalle.Where(x => x.RecetaId == id).Include(y => y.Ingrediente).ToListAsync();
            ViewData["Ingredientes"] = await _context.Ingredientes.ToListAsync();
            
            return View(recetaViewModel);


            /*
            if (id == null)
            {
                return NotFound();
            }

            var receta = await _context.Recetas.FindAsync(id);
            if (receta == null)
            {
                return NotFound();
            }
            return View(receta);
            */
        }

        // POST: Recetas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("RecetaId,Nombre,Descripcion,Fecha,Estado,UsuarioId")] Receta receta)
        public async Task<IActionResult> Edit(string Nombre, string Descripcion, IFormFile Imagen, bool Estado, string NombreImagen, string UsuarioId, int RecetaId)
        {

            if (Nombre != null && Descripcion != null)
            {
                Receta receta = new Receta();
                if (Imagen != null)
                {                    
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string nombreImagen = Path.GetFileNameWithoutExtension(Imagen.FileName);
                    string extension = Path.GetExtension(Imagen.FileName);
                    receta.NombreImagen = nombreImagen = DateTime.Now.ToString("yymmssfff") + extension;                  

                    string path = Path.Combine(wwwRootPath + "/image/" + nombreImagen);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await Imagen.CopyToAsync(fileStream);
                    }

                }
                else
                {
                    receta.NombreImagen = NombreImagen; 

                }

                receta.Nombre = Nombre;
                receta.Estado = Estado;
                receta.Descripcion = Descripcion;
                receta.Fecha = DateTime.Now;
                receta.UsuarioId = UsuarioId;
                receta.RecetaId = RecetaId;

                var recetaId = receta.RecetaId;

                try
                {
                    _context.Update(receta);                    

                    if (await _context.SaveChangesAsync() > 0)
                    {
                        var listaRecetaDetalle = _context.RecetaDetalle.Where(x => x.RecetaId == recetaId);
                        foreach (var recetaDetalle in listaRecetaDetalle)
                        {
                            _context.RecetaDetalle.Remove(recetaDetalle);
                            
                        }
                        await _context.SaveChangesAsync();

                        return Json(new { data = "ok" });
                    }
                    else
                    {
                        return Json(new { data = "error" });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecetaExists(receta.RecetaId))
                    {
                        return Json(new { data = "error" });
                    }

MisRecetasMT/Controllers/TipoIngredientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MisRecetasMT.Models.AccesoDB;
using MisRecetasMT.Models.Entidades;

namespace MisRecetasMT.Controllers
{
    
    public class TipoIngredientesController : Controller
    {
        private readonly Contexto _context;

        public TipoIngredientesController(Contexto context)
        {
            _context = context;
        }
        //[Authorize]

        // GET: TipoIngredientes
        public async Task<IActionResult> Index()
        {
            var tipoIngrediente = await _context.TipoIngrediente.ToListAsync();
            return View(tipoIngrediente);
            //return View(await _context.TipoIngrediente.ToListAsync());
        }

        // GET: TipoIngredientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoIngrediente = await _context.TipoIngrediente
                .FirstOrDefaultAsync(m => m.TipoIngredienteId == id);
            if (tipoIngrediente == null)
            {
                return NotFound();
            }

            return View(tipoIngrediente);
        }

        // GET: TipoIngredientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoIngredientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoIngredienteId,NombreTipoIngrediente,EstadoTipoIngrediente")] TipoIngrediente tipoIngrediente)
        {
            if (ModelState.IsValid)
            {
                TempData["Accion"] = "Crear";
                TempData["Mensaje"] = "El tipo de ingrediente se creó con éxito";

                _context.Add(tipoIngrediente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoIngrediente);
        }

        // GET: TipoIngredientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoIngrediente = await _context.TipoIngrediente.FindAsync(id);
            if (tipoIngrediente == null)
            {
                return NotFound();
            }
            return View(tipoIngrediente);
        }

        // POST: TipoIngredientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TipoIngredienteId,NombreTipoIngrediente,EstadoTipoIngrediente")] TipoIngrediente tipoIngrediente)
        {
            if (id != tipoIngrediente.TipoIngredienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoIngrediente);
                    await _context.SaveChangesAsync();
                    TempData["Accion"] = "Editar";
                    TempData["Mensaje"] = "El tipo de ingrediente se editó con éxito";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoIngredienteExists(tipoIngrediente.TipoIngredienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
               
            }
            return View(tipoIngrediente);
        }

        

        // POST: TipoIngredientes/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]        
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            /*
            var tipoIngrediente = await _context.TipoIngrediente.FindAsync(id);
            _context.TipoIngrediente.Remove(tipoIngrediente);
            await _context.SaveChangesAsync();
            TempData["Accion"] = "Eliminar";
            TempData["Mensaje"] = "El tipo de ingrediente se eliminó con éxito";
            return RedirectToAction(nameof(Index));
            */

            try
            {
                var tipoIngrediente = await _context.TipoIngrediente.FindAsync(id);

                if (tipoIngrediente.EstadoTipoIngrediente == true)
                {
                    tipoIngrediente.EstadoTipoIngrediente = false;

                }
                else
                {
                    tipoIngrediente.EstadoTipoIngrediente = true;
                }

                _context.Update(tipoIngrediente);
                await _context.SaveChangesAsync();
                TempData["Accion"] = "Editar";
                TempData["Mensaje"] = "Se cambió el estado con éxito";
                return RedirectToAction(nameof(Index));


            }
            catch (DbUpdateConcurrencyException)
            {
               
                
                throw;
                
            }
        }

        private bool TipoIngredienteExists(int id)
        {
            return _context.TipoIngrediente.Any(e => e.TipoIngredienteId == id);
        }
    }
}

MisRecetasMT/Views/Shared/_Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

MisRecetasMT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MisRecetasMT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.css">


    @RenderSection("Styles", required: false)


</head>
<body>
    <partial name="_Navbar" />
    <partial name="_Sidebar" />

    @RenderBody()


    <partial name="_Footer" />


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

MisRecetasMT/Views/Shared/_Navbar.cshtml
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Buscar" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="~/adminlte/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="~/adminlte/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="~/adminlte/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

MisRecetasMT/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
    <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/adminlte/dist//img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Mis Recetas</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/adminlte/dist//img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a asp-action="Index" asp-controller="Recetas" class="d-block">Bienvenido - @Context.Session.GetString("_Nombre")</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->


        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

            @{
                if (Context.Session.GetInt32("_Rol") == 1)
                {
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Usuarios" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                Usuarios
                            </p>
                        </a>
                    </li>
                    }
            }

            <li class="nav-item">
                <a asp-action="RecetasCompartidas" asp-controller="Recetas" class="nav-link">
                    <i class="nav-icon fas fa-share-alt"></i>                  
                    <p>
                        Recetas Compartidas

                    </p>
                </a>
            </li>



            <li class="nav-item">
                <a asp-action="Index" asp-controller="Recetas" class="nav-link">
                    <i class="nav-icon fas fa-utensils"></i>
                    <p>
                        Recetas

                    </p>
                </a>
            </li>

            @{
                if (Context.Session.GetInt32("_Rol") == 1)
                {


                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Ingredientes" class="nav-link">
                            <i class="nav-icon fas fa-cloud-meatball"></i>
                            <p>
                                Ingredientes

                            </p>
                        </a>
                    </li>

                } 
            }

            @{
                if (Context.Session.GetInt32("_Rol") == 1)
                {

                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="TipoIngredientes" class="nav-link">
                            <i class="nav-icon fas fa-carrot"></i>
                            <p>
                                Tipos de ingredientes

                            </p>
                        </a>
                    </li>
                } 
            }

            <li class="nav-item">
                <a asp-action="CerrarSesion" asp-controller="Usuarios" class="nav-link">
                    <i class="nav-icon fas fa-sign-out-alt"></i>
                    <p>
                        Cerrar Sesión
                        <span class="right badge badge-danger">Salir</span>
                    </p>
                </a>
            </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>